dist: trusty
sudo: required
group: deprecated-2017Q4


stages:
  - Build and Deploy
  - functional-test


matrix:
  include:
    - stage: Build and Deploy
      stages:
        - sub-stage1
        - sub-stage2
      matrix:
        include:
          - stage: sub-stage1
            script: echo "sub-stage1"
      env:
        - APP="Secrets"
      script: echo "something" ; exit 1
    - language: node_js
      script: echo $TRAVIS_PULL_REQUEST_BRANCH
    - sudo: true
      env:
        - APP="Monolith DB"
      script: echo ./test 1 # uses the default stage name "test"
    - script: echo ./test 2
      script: echo ./deploy mobile
    - script: echo ./deploy api 
      script: echo test3
      script: echo different test1
      script: echo $TRAVIS_BRANCH
      script: if [[ ${TRAVIS_BRANCH} != "master" ]]; then travis_terminate 0; fi
      script: echo mobile step
    - stage: functional-test
      script: echo api step
